# Production setup with local PostgreSQL
# Usage: docker-compose -f docker/compose.yml up -d --build
# Features: Production build, local database, no hot reload
services:
  better-chatbot:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NO_HTTPS=1
    env_file:
      - .env
    dns:
      - 8.8.8.8 # Google's public DNS server
      - 8.8.4.4 # Google's public DNS server
    networks:
      - better-chatbot-networks
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17
    env_file:
      - .env
    networks:
      - better-chatbot-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  localhost-helper:
    build:
      context: ../../../libs/dv01-shell-api-gateway/localhost-helper
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - UPSTREAM_SERVICE_URL=http://better-chatbot:3000
      - PROXY_SERVER_PORT=3002
      - PROXY_PATH=/chatbot
      - API_GATEWAY_URL=https://api-gateway.dv01.cloud
    env_file:
      - .env
    networks:
      - better-chatbot-networks
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  better-chatbot-networks:
    driver: bridge
